alterState(state => {
  const { data } = state;
  state.dataEl = (id, value) => {
    // function to return dataElement set with value
    return {
      dataElement: id,
      value: value,
    };
  };

  state.body = {
    program: data.program,
    programStage: data.programStage,
    orgUnit: data.orgUnit,
    trackedEntityInstance: data.trackedEntityInstance,
    enrollment: data.enrollment,
    eventDate: `${data.eventDate}T00:00:00.000`, // format;'2021-06-30T00:00:00.000'
    // enrollmentStatus: 'ACTIVE',
    // status: 'COMPLETED',
    // event: 'EZYHKe59NmY',
    //'attributeCategoryOptions': 'xYerKDKCefk',
    //'attributeOptionCombo': 'HllvX50cXC0',
    //'completedDate': '2021-10-06T00:00:00.000',
    //'completedBy': 'alokp@careindia.org',
    dataValues: [
      state.dataEl('j2jVjSzbBSl', state.data.j2jVjSzbBSl),
      state.dataEl('rcYhVWjKYOD', state.data.rcYhVWjKYOD),
      state.dataEl('Xq8IJfzYYhS', state.data.Xq8IJfzYYhS),
      state.dataEl('Xyb7MluqDXJ', state.data.Xyb7MluqDXJ),
      state.dataEl('qTDFqTP8e0N', state.data.qTDFqTP8e0N),
      state.dataEl('PRgM6afWahU', state.data.PRgM6afWahU),
      state.dataEl('YM06DHJEO0a', state.data.YM06DHJEO0a),
      state.dataEl('JQfbRTGVidD', state.data.JQfbRTGVidD),
      state.dataEl('TlHbxhC5JfB', state.data.TlHbxhC5JfB),
      state.dataEl('yW6TrE0jFi9', state.data.yW6TrE0jFi9),
      state.dataEl('dyQyFP0JoY2', state.data.dyQyFP0JoY2),
      state.dataEl('qW6AFETFUJE', state.data.qW6AFETFUJE),
      state.dataEl('I5MSJrFcsxW', state.data.I5MSJrFcsxW),
      state.dataEl('Fw7afYXVxFJ', state.data.Fw7afYXVxFJ),
      state.dataEl('FVr0DFR5kCu', state.data.FVr0DFR5kCu),
      state.dataEl('iZDxVnFcTFI', state.data.iZDxVnFcTFI),
      state.dataEl('BKdoGlB4SOB', state.data.BKdoGlB4SOB),
      state.dataEl('VLcaTEPGfT0', state.data.VLcaTEPGfT0),
      state.dataEl('b2Py4ojJBR1', state.data.b2Py4ojJBR1),
      state.dataEl('HNFNanis0Ks', state.data.HNFNanis0Ks),
      state.dataEl('wGerPbIW4kk', state.data.wGerPbIW4kk),
      state.dataEl('YHwV7ihDVpK', state.data.YHwV7ihDVpK),
      state.dataEl('hU2OFLeKSgN', state.data.hU2OFLeKSgN),
      state.dataEl('Q4UUFB1yfmp', state.data.Q4UUFB1yfmp),
      state.dataEl('USGkAMjWIQu', state.data.USGkAMjWIQu),
      state.dataEl('BkLLGIDLDHY', state.data.BkLLGIDLDHY),
      state.dataEl('k1hQG03dc65', state.data.k1hQG03dc65),
      state.dataEl('jFaNTptbVGK', state.data.jFaNTptbVGK),
      state.dataEl('nrz73zqkOGT', state.data.nrz73zqkOGT),
      state.dataEl('Ill0HFWS97A', state.data.Ill0HFWS97A),
      state.dataEl('qc0XmeYYYG1', state.data.qc0XmeYYYG1),
      state.dataEl('MkMvoZFlovk', state.data.MkMvoZFlovk),
      state.dataEl('UeDs5pHE0Gm', state.data.UeDs5pHE0Gm),
      state.dataEl('u10ZT6raeCg', state.data.u10ZT6raeCg),
      state.dataEl('uwTZmNJ2rWr', state.data.uwTZmNJ2rWr),
      state.dataEl('WL7drXWQWSt', state.data.WL7drXWQWSt),
      state.dataEl('BjQkMpNq7zU', state.data.BjQkMpNq7zU),
      state.dataEl('ZlXy62Mv7zk', state.data.ZlXy62Mv7zk),
      state.dataEl('jZBUQhVkjl9', state.data.jZBUQhVkjl9),
      state.dataEl('eYcfLEPSzKj', state.data.eYcfLEPSzKj),
      state.dataEl('Ji68ajPqNfo', state.data.Ji68ajPqNfo),
      state.dataEl('XimouRqX6Pq', state.data.XimouRqX6Pq),
      state.dataEl('eOILH0lOgtF', state.data.eOILH0lOgtF),
      state.dataEl('UyzB6KQlODO', state.data.UyzB6KQlODO),
      state.dataEl('bZyjhGG7qq1', state.data.bZyjhGG7qq1),
      state.dataEl('bB5gbi2XR2o', state.data.bB5gbi2XR2o),
      state.dataEl('DTUhQiiUQrj', state.data.DTUhQiiUQrj),
      state.dataEl('KVXjOQvsprZ', state.data.KVXjOQvsprZ),
      state.dataEl('DvmOnMN6A8O', state.data.DvmOnMN6A8O),
      state.dataEl('LbZje7Rlwh9', state.data.LbZje7Rlwh9),
      state.dataEl('DnIWT9KKADj', state.data.DnIWT9KKADj),
      state.dataEl('Rp0u3a0jdxd', state.data.Rp0u3a0jdxd),
      state.dataEl('vFDItUNKWfm', state.data.vFDItUNKWfm),
      state.dataEl('onMVDerKaWF', state.data.onMVDerKaWF),
      state.dataEl('KRFtvY6Nlnz', state.data.KRFtvY6Nlnz),
      state.dataEl('yGkM2FkQ5MO', state.data.yGkM2FkQ5MO),
      state.dataEl('D8R4lfgXOe2', state.data.D8R4lfgXOe2),
      state.dataEl('dJIRPfLRmQ7', state.data.dJIRPfLRmQ7),
      state.dataEl('WFXqLC2pN9M', state.data.WFXqLC2pN9M),
      state.dataEl('eqg9Kc7wjJt', state.data.eqg9Kc7wjJt),
      state.dataEl('ukea7GyxpMx', state.data.ukea7GyxpMx),
      state.dataEl('o4nWwW6tsvE', state.data.o4nWwW6tsvE),
      state.dataEl('aWEbwoHW7JD', state.data.aWEbwoHW7JD),
      state.dataEl('jjpcOKHh6JD', state.data.jjpcOKHh6JD),
      state.dataEl('za6HD8Vqm9D', state.data.za6HD8Vqm9D),
      state.dataEl('wcdPnip48LY', state.data.wcdPnip48LY),
      state.dataEl('YP71tdG5zcX', state.data.YP71tdG5zcX),
      state.dataEl('n1QurtQ7nVM', state.data.n1QurtQ7nVM),
      state.dataEl('hQtbBWVDwU6', state.data.hQtbBWVDwU6),
      state.dataEl('zl7Bd2mXTQq', state.data.zl7Bd2mXTQq),
      state.dataEl('Q37sRpGJau3', state.data.Q37sRpGJau3),
      state.dataEl('I8M7BE7xLkC', state.data.I8M7BE7xLkC),
      state.dataEl('DrDqT6EVULo', state.data.DrDqT6EVULo),
      state.dataEl('FcVjJIwE27V', state.data.FcVjJIwE27V),
      state.dataEl('ClVwgOWsq8x', state.data.ClVwgOWsq8x),
      state.dataEl('BzrerNYtvQm', state.data.BzrerNYtvQm),
      state.dataEl('aNiNMqjkXbM', state.data.aNiNMqjkXbM),
      state.dataEl('wKItc9secr2', state.data.wKItc9secr2),
      state.dataEl('HV4ye3f55mm', state.data.HV4ye3f55mm),
      state.dataEl('I9zXa6keqYy', state.data.I9zXa6keqYy),
      state.dataEl('i79aEz5ePH4', state.data.i79aEz5ePH4),
      state.dataEl('pFOVT0RwtLF', state.data.pFOVT0RwtLF),
      state.dataEl('xiyEfY9Jx6u', state.data.xiyEfY9Jx6u),
      state.dataEl('B3DG3me3Vxk', state.data.B3DG3me3Vxk),
      state.dataEl('ipHlKAVEMfz', state.data.ipHlKAVEMfz),
      state.dataEl('YxYWzVj4tU7', state.data.YxYWzVj4tU7),
      state.dataEl('KwUfjBTL5EO', state.data.KwUfjBTL5EO),
      state.dataEl('QPlXbsXp8Ge', state.data.QPlXbsXp8Ge),
      state.dataEl('KcLYyu7PHNe', state.data.KcLYyu7PHNe),
      state.dataEl('QbrU6ReY3Zq', state.data.QbrU6ReY3Zq),
      state.dataEl('mTOv1cnmvpx', state.data.mTOv1cnmvpx),
      state.dataEl('KPTx7FEtXgM', state.data.KPTx7FEtXgM),
      state.dataEl('qAmfhqLFsbV', state.data.qAmfhqLFsbV),
      state.dataEl('HtqQqS6cvwL', state.data.HtqQqS6cvwL),
      state.dataEl('opPwLeINEmF', state.data.opPwLeINEmF),
      state.dataEl('oMD1W0xV7Yr', state.data.oMD1W0xV7Yr),
      state.dataEl('Jn4n8OfMXYz', state.data.Jn4n8OfMXYz),
      state.dataEl('L4iVCs5duhL', state.data.L4iVCs5duhL),
      state.dataEl('CvjCwS1scFL', state.data.CvjCwS1scFL),
      state.dataEl('FQAZ72KH9Nk', state.data.FQAZ72KH9Nk),
      state.dataEl('c2Y3WtgmVWA', state.data.c2Y3WtgmVWA),
      state.dataEl('pL8tFrv0WZ1', state.data.pL8tFrv0WZ1),
      state.dataEl('Hd4Zshsu8XL', state.data.Hd4Zshsu8XL),
      state.dataEl('TZf8QKIQBs8', state.data.TZf8QKIQBs8),
      state.dataEl('W3baoVgbpow', state.data.W3baoVgbpow),
      state.dataEl('Bo3WVvQvGMT', state.data.Bo3WVvQvGMT),
      state.dataEl('TxHKDU5pqfR', state.data.TxHKDU5pqfR),
      state.dataEl('LXHsgPY5Dik', state.data.LXHsgPY5Dik),
      state.dataEl('d7kxsVHcrlR', state.data.d7kxsVHcrlR),
      state.dataEl('ZcrhvA0xVeq', state.data.ZcrhvA0xVeq),
    ],
  };
  console.log(`Request body: ${JSON.stringify(state.body, null, 2)}`);
  return state;
});
request({
  auth: {
    user: state.configuration.username,
    pass: state.configuration.password,
  },
  method: 'POST',
  url: 'https://testing.piirs.care.org/api/events',
  json: state => state.body,
});

alterState(state => {
  console.log(`Server response: ${JSON.stringify(state.body, null, 2)}`);
  return state;
});